services:
  postgres:
    image: postgres:16-alpine
    container_name: metrilive-postgres
    environment:
      POSTGRES_DB: metrilivedb
      POSTGRES_USER: metrilive
      POSTGRES_PASSWORD: vipit123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
